e-learning/config/routes.rb
Rails.application.routes.draw do
  resources :question_types
  resources :questioner_forms
  resources :answers
  resources :questions
  resources :tags
  resources :question_groups
  devise_for :users
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

e-learning/app/controllers/questioner_forms_controller.rb
class QuestionerFormsController < ApplicationController
  before_action :set_questioner_form, only: [:show, :edit, :update, :destroy]

  # GET /questioner_forms
  # GET /questioner_forms.json
  def index
    @questioner_forms = QuestionerForm.all
  end

  # GET /questioner_forms/1
  # GET /questioner_forms/1.json
  def show
  end

  # GET /questioner_forms/new
  def new
    @questioner_form = QuestionerForm.new
    @questioner_form.user_id = current_user.id
  end

  # GET /questioner_forms/1/edit
  def edit
  end

  # POST /questioner_forms
  # POST /questioner_forms.json
  def create
    @questioner_form = QuestionerForm.new(questioner_form_params)
    @questioner_form.user_id = current_user.id

    respond_to do |format|
      if @questioner_form.save
        format.html { redirect_to @questioner_form, notice: 'Questioner form was successfully created.' }
        format.json { render :show, status: :created, location: @questioner_form }
      else
        format.html { render :new }
        format.json { render json: @questioner_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questioner_forms/1
  # PATCH/PUT /questioner_forms/1.json
  def update
    respond_to do |format|
      if @questioner_form.update(questioner_form_params)
        format.html { redirect_to @questioner_form, notice: 'Questioner form was successfully updated.' }
        format.json { render :show, status: :ok, location: @questioner_form }
      else
        format.html { render :edit }
        format.json { render json: @questioner_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questioner_forms/1
  # DELETE /questioner_forms/1.json
  def destroy
    @questioner_form.destroy
    respond_to do |format|
      format.html { redirect_to questioner_forms_url, notice: 'Questioner form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_questioner_form
      @questioner_form = QuestionerForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def questioner_form_params
      params.require(:questioner_form).permit(:user_id, question, {answer_ids: []})
    end
end

e-learning/app/helpers/questioner_forms_helper.rb
module QuestionerFormsHelper
end

e-learning/app/views/questioner_forms/_form.html.erb
<%= form_for(questioner_form) do |f| %>
  <% if questioner_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(questioner_form.errors.count, "error") %> prohibited this questioner_form from being saved:</h2>

      <ul>
      <% questioner_form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div>
      <%= f.label :question, "QUESTION" %>
    </div>
    <ol>
       <% Question.order('RANDOM()').each do |obj| %>
        <%= f.hidden_field :question_id, { :value => obj.id} %>
        <li>
          <div><%= obj.text %></div>
          <div class="radio" style="margin-left:30px;">
            <% obj.answer.all.each do |answer| %>
              <%= f.radio_button :answer_id, answer.text %>
              <%= f.label obj.id, answer.text %>
            <% end %>
          </div>

        </li>
      <% end %>
    </ol>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

e-learning/app/views/questioner_forms/edit.html.erb
<h1>Editing Questioner Form</h1>

<%= render 'form', questioner_form: @questioner_form %>

<%= link_to 'Show', @questioner_form %> |
<%= link_to 'Back', questioner_forms_path %>

e-learning/app/views/questioner_forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questioner Forms</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>User</th>
      <th>Answer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questioner_forms.each do |questioner_form| %>
      <tr>
        <td><%= questioner_form.user.try(:name) %></td>
        <td><%= questioner_form.answer.try(:text) %></td>
        <td><%= link_to 'Show', questioner_form %></td>
        <td><%= link_to 'Edit', edit_questioner_form_path(questioner_form) %></td>
        <td><%= link_to 'Destroy', questioner_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Questioner Form', new_questioner_form_path %>

e-learning/app/views/questioner_forms/new.html.erb
<h1>New Questioner Form</h1>

<%= render 'form', questioner_form: @questioner_form %>

<%= link_to 'Back', questioner_forms_path %>

e-learning/app/views/questioner_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @questioner_form.question %>
</p>

<p>
  <strong>User:</strong>
  <%= @questioner_form.user %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @questioner_form.answer %>
</p>

<%= link_to 'Edit', edit_questioner_form_path(@questioner_form) %> |
<%= link_to 'Back', questioner_forms_path %>